# .github/workflows/main.yml
name: Main CI
 
on:
  pull_request:
    branches:
      - dev 
jobs:
  deploy:
    uses: KadirvelA/gitops-sample/.github/workflows/qa.yml@dev
    with:
      app_location: '/'  # Input passed to reusable workflow
      output_location: '.'  # Input passed to reusable workflow
      azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}